# Generated by Django 4.1.7 on 2023-12-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type_task', models.CharField(choices=[('Поставить лайк', 'Поставить лайк'), ('Сделать репост', 'Сделать репост'), ('Написать комментарий', 'Написать комментарий')], max_length=36)),
                ('link', models.CharField(max_length=100)),
                ('reward', models.FloatField(default=0)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Все статусы', 'Все статусы'), ('Активные', 'Активные'), ('Остановленные', 'Остановленные'), ('Завершенные', 'Завершенные'), ('В очереди', 'В очереди'), ('На модерации', 'На модерации'), ('Заблокированные', 'Заблокированные')], max_length=36)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateTimeField()),
                ('status', models.CharField(max_length=36)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
